### ISSUE TITLE
mbTiles can not be found

### ISSUE THREAD

**Issue by janedzumerko** [0nza1101/ionic3-leaflet-mbtiles#1]
I also want to implement offline map using mbtiles and leaflet.
But when I am trying to implement this in my project I got build issue that says 'mbTiles can not be found', and the line of the error is **let mb = L.tileLayer.mbTiles('assets/tiles/countries-raster.mbtiles', {**
Any thoughts what am I missing?

**Comment by 0nza1101** [comment]
Hello,
Thanks for your feedback, I updated repo to make implementation much more easier.
