### ISSUE TITLE
can this work with mbtiles in android native filesystem

### ISSUE THREAD

**Issue by 543802360** [0nza1101/ionic3-leaflet-mbtiles#11]
thank you for your good job.I have a question，can this work with mbtiles in android native filesystem.I mean the mbties is not in the code project  ‘assets/XX’

**Comment by 0nza1101** [comment]
Try but I think it can since it reference a path that give an ArrayBuffer maybe you will need to use a cordova plugin to retrieve the path.

**Comment by rorp24** [comment]
yes it work. You have to do like this:
import:
`import { File } from '@ionic-native/file/ngx'
import {WebView} from '@ionic-native/ionic-webview'`
code:
`var pathToFile = this.file.externalDataDirectory+"path/to/your/file/yourFile";
			var truePath = WebView.convertFileSrc(pathToFile);
			L.tileLayer.mbTiles(truePath,{
				maxZoom: 18,
				attribution: "local"
			}).addTo(this.map)`
