### ISSUE TITLE
13 seconds to load in map

### ISSUE THREAD

**Issue by hawk2017** [0nza1101/ionic3-leaflet-mbtiles#12]
i wonder what will happen if i build this on device. any work around how to speed up the process loading the mbtiles. thanks in advance

![test](https://user-images.githubusercontent.com/26212308/43988887-96c91a14-9d71-11e8-8e55-753daa20e9f9.png)

**Comment by 0nza1101** [comment]
It should be I'm a bit busy these days, for the moment export your 194Mb .mbtiles to png format using mbutil and reduce pngs quality with [pngquant](https://pngquant.org/) then repack it in .mbtiles using [mbutil](https://github.com/mapbox/mbutil)

**Comment by hawk2017** [comment]
thank you! as of now i'm trying to work for this plugin in ionic 2 https://github.com/afsuarez/mapsforge-cordova-plugin using mapsforge map. you can download here http://download.mapsforge.org/ howerver hope this will work.

**Comment by hawk2017** [comment]
also found this bug  when trying to run on device
MBTiles DB error
main.js:84
Object {error: RangeError: Array buffer allocation failed
