### ISSUE TITLE
What is the size limit after the plugin stop working?

### ISSUE THREAD

**Issue by rorp24** [0nza1101/ionic3-leaflet-mbtiles#14]
pretty explicit question, but their is the details:
I use the plugin to make an app that read mbtiles from app files storage (see issue #11 for how i make it work). But their is my problem:
when I use the demo file it work, but when I use big files (880 Mo and more), my app crash. So that why I ask for "What is the size limit after the plugin stop working?"

**Comment by dapingtai** [comment]
I have the same situation, is that problem resolved?

**Comment by 0nza1101** [comment]
Since a .mbtiles is just a specification for storing tiled map data in an SQLite database its follow the SQLite limits described at: http://www.sqlite.org/limits.html
