### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/ionic3-leaflet-mbtiles#2]
Hello, really thank you for your offline map support.

It works well at browser but when I built this source for real Android device and ran on Android 6.0.1.
As soon as the App starts, it'll meet the error and cannot proceed more. 

Build Environment like this:
Cordova 7.1.0
Cordova android 6.3.0

**Comment by 0nza1101** [comment]
Hello,
I updated repo to make implementation much more easier. Tell me if this is working for you now.

**Comment by JeongJun-Lee** [comment]
You updated README. Now do I not need to patch more both index-Android.js  and index-Android.js. But there are errors like this:

![image](https://user-images.githubusercontent.com/11474775/34649604-616ce342-f3d4-11e7-8512-7427e6fca4c6.png)

**Comment by 0nza1101** [comment]
You should use the npm package that I made [leaflet-tilelayer-mbtiles-ts](https://www.npmjs.com/package/leaflet-tilelayer-mbtiles-ts)

`npm i leaflet-tilelayer-mbtiles-ts --save`

You should also rename the import.
Clone the repo and give it a try.

**Comment by JeongJun-Lee** [comment]
Thank you. I replaced old one with the new package. I works well at browser but this error is still at real device.
