### ISSUE TITLE
White blank screen at real Android device

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/ionic3-leaflet-mbtiles#6]
I have cloned with clean state by git clone and build and installed to Android device.
But it shows only blank white screen with this errors.
But It works well at only browser by ionic serve.

![image](https://user-images.githubusercontent.com/11474775/38162029-63fd776a-34f3-11e8-9a42-8f0d25994e7f.png)

**Comment by jpujol880807** [comment]
I just had to use an online map, seems it doesn't work with android
