### ISSUE TITLE
Broken map screen at iOS simulator.

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/ionic3-leaflet-mbtiles#7]
I have cloned with clean state by git clone and build and installed to iOS simulator.
But it shows only broken map screen like below.
But It works well at only browser by ionic serve.

![image](https://user-images.githubusercontent.com/11474775/38162039-9ceb3b52-34f3-11e8-93a0-2fecb0a6dc79.png)

**Comment by 0nza1101** [comment]
Its working for me in prod build see image below

<img width="322" alt="screen shot 2018-04-05 at 19 46 00" src="https://user-images.githubusercontent.com/13056641/38382457-54b2e61c-390a-11e8-9569-b0ef289f8f27.png">

**Comment by JeongJun-Lee** [comment]
This issue is from not loading leaflet.css in index.html when at first the App started in offline.

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />

**Comment by 0nza1101** [comment]
Of course you need to load leaflet.css in index.html from a local folder if you want to use leaflet offline.
