### ISSUE TITLE
It doesn't work with lazy loading at real Android device.

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/ionic3-leaflet-mbtiles#8]
When I load this 3party library with lazy loading, it shows this error like below.

![image](https://user-images.githubusercontent.com/11474775/38177456-4bb7ad82-361b-11e8-9731-b06583a4b4df.png)

**Comment by 0nza1101** [comment]
Can you give me more information or some code about the issue please ?

**Comment by JeongJun-Lee** [comment]
I changed the HomePage to be loaded by lazy loading like below link.
https://blog.ionicframework.com/ionic-and-lazy-loading-pt-1/

**Comment by 0nza1101** [comment]
The issue is not caused by the lazy loading but by your code if you can give me a sample project with the error, this will help me to figure out.
